// ─── ESTILOS COMPARTIDOS ─────────────────────────────────────────────
// Extraído de App.js durante el refactor a páginas. Cualquier página que
// necesite estos estilos base los importa de aquí. Los estilos que solo
// usa una página pueden quedarse inline en esa página.
export const S = {
  app:   { fontFamily:"'DM Sans', sans-serif", minHeight:'100vh', background:'#f0f0f7', display:'flex', justifyContent:'center' },
  phone: { width:'100%', maxWidth:420, minHeight:'100vh', background:'#f0f0f7', position:'relative', paddingBottom:88 },
  header:{ background:'linear-gradient(135deg,#5b21b6 0%,#7c3aed 45%,#4f46e5 100%)', padding:'52px 24px 72px', position:'relative', overflow:'hidden' },
  bubble:(t,r,b,l,w,h,op)=>({ position:'absolute', top:t, right:r, bottom:b, left:l, width:w, height:h, borderRadius:'50%', background:`rgba(255,255,255,${op})`, pointerEvents:'none' }),
  hContent:{ position:'relative', zIndex:2 },
  topRow:  { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:20 },
  greeting:{ color:'rgba(255,255,255,0.7)', fontSize:13, marginBottom:3 },
  userName:{ color:'#fff', fontSize:20, fontWeight:800 },
  avatarCircle:{ width:40, height:40, borderRadius:'50%', background:'rgba(255,255,255,0.2)', border:'2px solid rgba(255,255,255,0.4)', display:'flex', alignItems:'center', justifyContent:'center' },
  balLabel: { color:'rgba(255,255,255,0.65)', fontSize:11, letterSpacing:1, textTransform:'uppercase', marginBottom:4 },
  balAmount:{ color:'#fff', fontSize:36, fontWeight:800, letterSpacing:-1, lineHeight:1 },
  pillRow:  { display:'flex', gap:8, marginTop:16 },
  pill:(active)=>({ padding:'7px 18px', borderRadius:20, border:'none', cursor:'pointer', fontSize:12, fontWeight:700, background:active?'#fff':'rgba(255,255,255,0.18)', color:active?'#7c3aed':'#fff', transition:'all 0.2s' }),
  statsRow: { display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:10, padding:'0 16px', marginTop:-36, marginBottom:16, position:'relative', zIndex:10 },
  statsRowWithAlerts: { display:'grid', gridTemplateColumns:'1fr 1fr 1fr', gap:10, padding:'0 16px', marginTop:16, marginBottom:16, position:'relative', zIndex:10 },
  statCard: { background:'#fff', borderRadius:16, padding:'12px 10px', boxShadow:'0 4px 20px rgba(91,33,182,0.12)', display:'flex', flexDirection:'column', alignItems:'center', gap:4 },
  statIconWrap:(color)=>({ width:30, height:30, borderRadius:10, background:color+'18', display:'flex', alignItems:'center', justifyContent:'center' }),
  statLabel:{ fontSize:10, color:'#9ca3af', fontWeight:600 },
  statVal:(color)=>({ fontSize:14, fontWeight:800, color }),
  section:  { padding:'0 16px', marginBottom:14 },
  secHeader:{ display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:10 },
  secTitle: { fontSize:15, fontWeight:700, color:'#1f1b4b' },
  seeAll:   { display:'flex', alignItems:'center', gap:2, fontSize:11, color:'#7c3aed', fontWeight:700, background:'none', border:'none', cursor:'pointer' },
  card:     { background:'#fff', borderRadius:20, padding:'14px', marginBottom:10, boxShadow:'0 2px 12px rgba(0,0,0,0.05)' },
  chartToggle:{ display:'flex', gap:6 },
  chartBtn:(active)=>({ padding:'5px 14px', borderRadius:20, border:'none', cursor:'pointer', background:active?'linear-gradient(135deg,#7c3aed,#4f46e5)':'#f5f3ff', color:active?'#fff':'#7c3aed', fontSize:11, fontWeight:700, transition:'all 0.2s' }),
  txItem:(last)=>({ display:'flex', alignItems:'center', gap:10, padding:'9px 0', borderBottom:last?'none':'1px solid #f5f3ff' }),
  txIconWrap:(color)=>({ width:40, height:40, borderRadius:13, background:color+'18', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }),
  txName:{ fontSize:13, fontWeight:700, color:'#1f1b4b', marginBottom:2 },
  txMeta:{ fontSize:11, color:'#9ca3af' },
  txAmt:(tipo)=>({ marginLeft:'auto', fontSize:14, fontWeight:800, flexShrink:0, color:tipo==='ingreso'?'#10b981':'#ef4444' }),
  actionBtn:(bg)=>({ width:30, height:30, borderRadius:9, background:bg, border:'none', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', flexShrink:0 }),
  catRow:  { marginBottom:12 },
  catTop:  { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:5 },
  catName: { display:'flex', alignItems:'center', gap:7, fontSize:12, fontWeight:600, color:'#1f1b4b' },
  catAmt:  { fontSize:12, fontWeight:800, color:'#ef4444' },
  progBg:  { background:'#f5f3ff', borderRadius:100, height:5, overflow:'hidden' },
  progFill:(color,pct)=>({ width:`${pct}%`, height:'100%', background:color, borderRadius:100, transition:'width 1s' }),
  pageHeader:(g)=>({ background:g||'linear-gradient(135deg,#5b21b6,#7c3aed)', padding:'52px 24px 28px', position:'relative', overflow:'hidden' }),
  pageTitle:{ color:'#fff', fontSize:20, fontWeight:800, position:'relative', zIndex:2 },
  pageSub:  { color:'rgba(255,255,255,0.6)', fontSize:13, marginTop:4, position:'relative', zIndex:2 },
  formWrap: { padding:'16px' },
  formCard: { background:'#fff', borderRadius:24, padding:'20px', boxShadow:'0 4px 24px rgba(91,33,182,0.1)' },
  typeToggle:{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:8, marginBottom:16 },
  typeBtn:(active,tipo)=>({ padding:'12px', borderRadius:14, border:`2px solid ${active?(tipo==='ingreso'?'#10b981':'#ef4444'):'#f0eeff'}`, background:active?(tipo==='ingreso'?'#f0fdf4':'#fef2f2'):'#fafaf9', color:active?(tipo==='ingreso'?'#10b981':'#ef4444'):'#9ca3af', fontWeight:700, fontSize:14, cursor:'pointer', fontFamily:'inherit', transition:'all 0.2s', display:'flex', alignItems:'center', justifyContent:'center', gap:6 }),
  label:  { display:'block', fontSize:11, fontWeight:700, color:'#9ca3af', letterSpacing:0.5, textTransform:'uppercase', marginBottom:6 },
  input:  { width:'100%', padding:'12px 14px', borderRadius:12, border:'2px solid #f0eeff', fontSize:14, fontFamily:'inherit', outline:'none', boxSizing:'border-box', color:'#1f1b4b', background:'#fafaf9', marginBottom:12, transition:'border 0.2s' },
  select: { width:'100%', padding:'12px 14px', borderRadius:12, border:'2px solid #f0eeff', fontSize:14, fontFamily:'inherit', background:'#fafaf9', color:'#1f1b4b', marginBottom:16, outline:'none' },
  submitBtn:{ width:'100%', padding:'14px', background:'linear-gradient(135deg,#7c3aed,#4f46e5)', color:'#fff', border:'none', borderRadius:14, fontSize:15, fontWeight:700, fontFamily:'inherit', cursor:'pointer', boxShadow:'0 4px 16px rgba(124,58,237,0.35)', display:'flex', alignItems:'center', justifyContent:'center', gap:8 },
  bottomNav:{ position:'fixed', bottom:0, left:'50%', transform:'translateX(-50%)', width:'100%', maxWidth:420, background:'#fff', borderTop:'1px solid #ede9fe', display:'flex', justifyContent:'space-around', alignItems:'center', padding:'8px 0 20px', boxShadow:'0 -4px 20px rgba(91,33,182,0.08)', zIndex:100 },
  navBtn:  { display:'flex', flexDirection:'column', alignItems:'center', gap:3, background:'none', border:'none', cursor:'pointer', padding:'4px 14px' },
  navLabel:(active)=>({ fontSize:9, fontWeight:700, color:active?'#7c3aed':'#9ca3af' }),
  fab:     { width:50, height:50, borderRadius:'50%', background:'linear-gradient(135deg,#7c3aed,#4f46e5)', display:'flex', alignItems:'center', justifyContent:'center', boxShadow:'0 4px 16px rgba(124,58,237,0.45)', border:'none', cursor:'pointer', marginTop:-18 },
};

// Helpers de foco/blur para inputs (repetidos en varias páginas)
export const enfocar   = (e) => { e.target.style.borderColor = '#7c3aed'; };
export const desenfocar= (e) => { e.target.style.borderColor = '#f0eeff'; };
